#!/bin/sh

if [ "$1" = "true" ]
then 
  # Battery
  # Dim screen
  echo 0 > /sys/class/backlight/acpi_video0/brightness
  # 300s before standby and suspend, 60s monitor off
  xset dpms 100 100 100
else
  # AC
  # Full brightness
  echo 0 > /sys/class/backlight/acpi_video0/brightness
  # 300s before standby suspend and monitor off
  xset dpms 300 300 300
fi
